### ISSUE TITLE
Deep Multi-User Reinforcement Learning for Distributed Dynamic Spectrum Access

### ISSUE THREAD

**Issue by Windy-with-sky** [T-E-K-N-A-S/Major2#1]
Hello, do you have the simulation code for this article?

**Comment by teknasd** [comment]
Follow this repository https://github.com/shkrwnd/Deep-Reinforcement-Learning-for-Dynamic-Spectrum-Access. this has more resources.

**Comment by Windy-with-sky** [comment]
Thank you very much

**Comment by lpengxue** [comment]
> Follow this repository https://github.com/shkrwnd/Deep-Reinforcement-Learning-for-Dynamic-Spectrum-Access. this has more resources.

Hello, I have reproduced the simulation code in the link.   Can you share the simulation code used in these diagrams?  Thank you very much. 
![image](https://github.com/teknasd/Major2/assets/43953165/0c4d2661-fd9a-4132-8fba-5fd11a727559)
